### ISSUE TITLE
COUNTERFEIT FROG CHECKING GOPHER DOES NOT WISH TO CONNECT

### ISSUE THREAD

**Issue by zgrep** [FROG-TIPS/frog.tips-api#11]
UPON THE [PUBLIC REVEAL](https://twitter.com/FrogTips/status/754694456276910081) OF THE COUNTERFEIT FROG REGISTRY, COUNTLESS HEAPS OF PEOPLE HAVE ATTEMPTED TO CHECK THEIR FROG'S UNIQUE ID. THEY HAVE ALL BEEN [REJECTED](http://gopher.floodgap.com/gopher/gw?a=gopher%3A%2F%2Ffrog.tips%2FGENUINEFROG) BY THE GOPHER IN CHARGE.

UPON MY ATTEMPTS TO CONTACT THE GOPHER, I HAVE FAILED TO MAKE ANY SORT OF PRIVATE OR CORPORATE CONNECTION. THE GOPHER SIMPLY REFUSES TO NETWORK, SOCIALLY OR OTHERWISE.

PLEASE CONVINCE THE FROG VERIFICATION GOPHER TO START VERIFYING FROGS. THIS IS OF VITAL IMPORTANCE, THE COUNTERFEIT FROG TRADE MUST BE STOPPED.

**Comment by perlisweird** [comment]
Hello Sir,

FROG SYSTEMS engineers are hard at work on a Gopher server. Before you know it, that little guy will be poking his head out of the dirt and you'll be in a right fit about it.

Please wait patiently for like two days or something. Yeah.

**Comment by perlisweird** [comment]
Please stop posting pictures of feet to this newsgroup. This is a Doctor Who newsgroup and we don't want to see pictures of your naked feet. Thank you.

**Comment by ghost** [comment]
Hello. We sincerely apologise for sending feet. We were confused and misled by the very foot-oriented pictures of David Tennant that were being sent around. We shall refrain from doing so in the future.

**Comment by FireyFly** [comment]
No more pictures of feet? What is this travesty!? I came here to lay my eyes upon the supple beauty of uncovered, leg-enabled appendages, and instead I get a rude message asking me to cease the source of my utmost happiness. You are all savages, all of you!

**Comment by perlisweird** [comment]
This is exactly the kind of behavior that caused us to close down the forums.
