### ISSUE TITLE
IS FROG COMPATIBLE WITH WINE

### ISSUE THREAD

**Issue by keeferrourke** [FROG-TIPS/frog.tips-api#14]
FROG.TIPS TIP 85 VERY HELPFULLY SUGGESTS THAT FROG SHOULD NOT COME IN CONTACT WITH VODKA (GOOD TO KNOW). FROG IS NOT COMPATIBLE WITH LIQUOR (I WOULD NOT HAVE KNOWN THIS).

![screenshot from 2016-08-30 19-19-11](https://cloud.githubusercontent.com/assets/6888381/18110547/a6251b54-6ee6-11e6-8497-d969f8c9b165.png)

FROG [README](https://github.com/FROG-TIPS/frog.tips-api/blob/master/README.rst) SAYS FROG MUST BE CLEANED WITH 100% ALCOHOL SOLUTION ONLY. 100% ALCOHOL SOLUTION IS MUCH STRONGER THAN LIQUOR.

IS FROG COMPATIBLE WITH WINE.

**Comment by perlisweird** [comment]
FROG IS ONLY COMPATIBLE WITH WINE IF ASSIGNED THE NAME "JEREMIAH" IN THE FIRMWARE ([#1103](https://frog.tips/#1103)). FROG'S FIRMWARE CAN BE FOUND AT [GOPHER://GOPHER.FROG.TIPS/FIRMWARE_V2](http://gopher.floodgap.com/gopher/gw?gopher://gopher.frog.tips:70/0/FIRMWARE_V2).

THE README USES THE WORD "ALCOHOL" IN THE COLLOQUIAL SENSE; YOU MAY CLEAN FROG WITH ISOPROPYL ALCOHOL (RUBBING ALCOHOL) BUT MAY NOT USE ETHYL ALCOHOLS (DRINKING ALCOHOL) TO FUEL OR TOUCH FROG.

THANK YOU FOR NOTING THAT THE TIPS ARE HELPFUL. WE TRY TO BE HELPFUL HERE AT FROG SYSTEMS.

**Comment by perlisweird** [comment]
FIXED IN 77387e5072db4cf685995c82751d610f7509c892

**Comment by perlisweird** [comment]
REOPENING THIS WHILE I CLEAN THE CAT LITTER.

**Comment by perlisweird** [comment]
TURNS OUT IT WAS CLEANED. VERY CURIOUS. OPENING A SEPARATE ISSUE.
