### ISSUE TITLE
FIX HTTPS

### ISSUE THREAD

**Issue by perlisweird** [FROG-TIPS/frog.tips-api#16]
YES WE KNOW THE CA IS NOW INVALID. PLEASE STOP SENDING MAIL AS IT'S VERY COSTLY TO FLY IT TO OUR REMOTE SITE AND WE'D MUCH RATHER THE AIRPLANE BE USED FOR MEDICINE AND COMFORT MAGAZINES.

**Comment by chrispbs** [comment]
THIS ISSUE HAS BEEN RESOLVED BY THE FROG INCIDENT RESPONSE TEAM. FROG SYSTEMS INC. TLS CERTIFICATES ARE NOW SIGNED BY LET'S ENCRYPT.

DESPITE THE NAME OF THE CERTIFICATE AUTHORITY NOW USED BY FROG SYSTEMS INC., "LET'S ENCRYPT" SHOULD NOT BE TAKEN AS A RECOMMENDATION, PERSUASION OR OBLIGATION TO ENCRYPT YOUR FROG. BY DOING SO, FROG WILL BECOME PARANOID AND WILL NO LONGER COMMUNICATE WITH THE OUTSIDE WORLD. SEVERE DATA LOSS WILL OCCUR.

THANK YOU FOR HELPING TO KEEP FROG SECURE.
