### ISSUE TITLE
FROG.TIPS MAINFRAME USES SELF-SIGNED CERTIFICATE

### ISSUE THREAD

**Issue by adiabatic** [FROG-TIPS/frog.tips-api#9]
FROG.TIPS HAS HELPED ME USE MY FROG BETTER BUT I'M WORRIED THAT MY FROG TIPS MAY BE INTERCEPTED AND/OR MODIFIED BY A THIRD PARTY IN TRANSIT. FURTHER, I WOULD LIKE TO BE ABLE TO SEND OTHER PEOPLE TO THE FROG.TIPS MAINFRAME WITHOUT HAVING TO WORRY THAT THEIR TIPS MIGHT BE MODIFIED TO SAY "FROGS ARE BEST CLEANED IN TIDE FREE AND GENTLE HIGH EFFICIENCY LIQUID LAUNDRY DETERGENT". SAID OTHER PEOPLE ARE SUSPICIOUS OF SELF-SIGNED CERTIFICATES. WOULD IT BE POSSIBLE TO GET AN OTHER-SIGNED CERTIFICATE FOR THE FROG.TIPS MAINFRAME SO I MAY BE ASSURED THAT I HELP DISSEMINATE THE UNALTERED, HIGHEST-QUALITY FROG TIPS ON THE INTERNET?

**Comment by perlisweird** [comment]
THANK YOU FOR POINTING OUT THIS SECURITY FLAW WITH FROG.TIPS.

FROG SYSTEMS ENGINEERS ARE CURRENTLY WORKING ON OBTAINING A CERTIFICATE FROM THE PROPER AUTHORITIES. DO YOU HAVE ANY SUGGESTIONS AS TO HOW TO EXPEDITE THE PROCESS?

FROG IS NOT SECURE BY DEFAULT. YOU MUST HARDEN FROG BY REPEATEDLY EXPOSING IT TO THE STRESSES OF THE WORLD.

**Comment by adiabatic** [comment]
JUST THIS PAST WEEK I TAUGHT A BUNCH OF AFRICAN GROUND SQUIRRELS HOW TO GET CERTIFICATES FROM AUTHORITIES. I THINK I HAVE ALSO TAUGHT THEM HOW TO RENEW CERTIFICATES BUT I'M NOT 100% SURE YET. THEY SEEM TO BE ABLE TO RENEW FAKE CERTIFICATES, THOUGH.

I HAVE MY SQUIRREL CARRY AROUND A RUSSIAN ENGINE AND A GOPHER. PEOPLE TALK TO THE ENGINE AND THE ENGINE TALKS TO THE GOPHER AND TELLS PEOPLE WHAT THE GOPHER SAID TO TELL THEM. WHEN I LOOKED INTO HAVING SQUIRRELS GET CERTIFICATES FROM FOXLIZARDS USING THE FOXLIZARD CERTIFICATE KIT, I LEARNED THERE WERE TWO OPTIONS:
- PUT AWAY THE RUSSIAN ENGINE SO IT CAN'T TALK TO PEOPLE, THEN HAVE THE SQUIRREL USE A STANDALONE FOXLIZARD MEGAPHONE (IT COMES WITH THE KIT) FOR 15–30 SECONDS, THEN PUT THE RUSSIAN ENGINE BACK
- HAVE THE KIT RADIO THE FOXLIZARDS BY ITSELF, THEN HAVE THE RUSSIAN ENGINE TALK TO FOXLIZARDS OUT OF THE CORNER OF ITS MOUTH FOR 15–30 SECONDS WHILE IT RELAYS GOPHER TALK NORMALLY

I WAS OK WITH USING A STANDALONE MEGAPHONE BEFORE HAVING MY SQUIRREL SET UP THE ENGINE, BUT ONCE I HAVE THE ENGINE RUNNING I DON'T WANT IT TO STOP. IF THE GOPHER IS MISSING OR SICK THE ENGINE ITSELF IS SMART ENOUGH TO TELL PEOPLE "THE GOPHER IS OUT AMONG ONE OF HIS FIVE HUNDRED AND THREE HOLES, IT'S NOT YOUR FAULT, COME BACK LATER IF YOU WANT TO HEAR MORE FROM THE GOPHER", BUT IF THE ENGINE IS GONE THE PEOPLE GET NOTHING.

OF COURSE, YOU DO NOT USE A RUSSIAN ENGINE TO TALK TO PEOPLE — YOU USE DRUNK SNAKES DIRECTLY WITHOUT A MIDDLEMAN.

ASSUMING YOU WANT YOUR DRUNK SNAKES TO TELL PEOPLE HOW TO USE THEIR FROGS 24/7, YOU WILL NEED TO FIND A WAY TO HAVE THEM PASS MESSAGES THAT THE FOXLIZARDS ARE LOOKING FOR. I HAVE WORKED A LITTLE TINY BIT WITH DRUNK SNAKES AND THIS WOULD PROBABLY NOT BE TOO DIFFICULT.

I HAVE AN ANSIBLE THAT I WROTE THAT TELLS SQUIRRELS HOW TO GET CERTIFICATES FROM FOXLIZARDS BUT IT HAS A LOT OF STUFF ABOUT WHAT THE GOPHER SAYS. I WOULD PUT THE ANSIBLE ON THE INTERNET FOR ALL TO SEE AND GET INTERNET POINTS FROM IT, BUT I WOULD HAVE TO DO MORE WORK THAN I WANT TO MAKE SURE THE ANSIBLE NEVER SAYS ANYTHING ABOUT WHAT THE GOPHER SAYS.

I COULD REMOVE ALL THE GOPHER BITS FROM THE ANSIBLE AND IT _MIGHT_ MAKE SENSE STILL, BUT IT MIGHT BREAK TOO BECAUSE I DON'T WANT TO TEST IT WITHOUT THE GOPHER PARTS OF THE ANSIBLE TRANSMISSION.

GIVE ME A FEW DAYS AND I **MIGHT** BE ABLE TO SCRUB THE ANSIBLE TRANSMISSION OF WHAT THE GOPHER SAYS TO PEOPLE AND WHAT IT SAYS TO THE ELEPHANT (OF COURSE IT TALKS TO AN ELEPHANT, THAT'S HOW IT KNOWS WHAT TO SAY TO PEOPLE THROUGH THE RUSSIAN ENGINE). IF I CAN'T TOTALLY SCRUB THE ANSIBLE I MIGHT JUST CREATE ANOTHER PRIVATE REPO FOR A FEW DAYS WITH A PARTIALLY-SCRUBBED ANSIBLE IN IT, AND GIVE YOU GUYS CONTRIBUTOR ACCESS.

**Comment by perlisweird** [comment]
MARKING AS WALLOFTEXT, WONTFIX.

OUR TEAM OF HIGHLY ADMIRED ENGINEERS WILL ADDRESS THIS ISSUE FOR THE NEXT MILESTONE.

**Comment by perlisweird** [comment]
SOME GUY WANDERED IN AND IS FIXING THIS NOW

**Comment by chrispbs** [comment]
THIS ISSUE HAS BEEN TRANSFERRED TO THE FROG INCIDENT RESPONSE TEAM. WE WILL ASSESS THE SEVERITY OF THE PROBLEM AND ISSUE A FIX IN DUE COURSE.

THANK YOU FOR HELPING TO KEEP FROG SECURE.

**Comment by chrispbs** [comment]
HTTPS://FROG.TIPS IS NOW BEING SERVED USING ONLY THE HIGHEST-QUALITY PUBLIC KEY CRYPTFROGRAPHY WITH A TLS CERTIFICATE SIGNED BY A CERTIFICATE AUTHORITY IN THE TRUST STORE OF ALL MODELS OF FROG CURRENTLY ON THE MARKET. PLEASE RETURN FROG TO YOUR NEAREST SERVICE CENTER OR DEALERSHIP IF FROG VOMITS UPON ENCOUNTERING THE NEW CERTIFICATE.

THANK YOU FOR HELPING TO KEEP FROG SECURE.

**Comment by perlisweird** [comment]
THANK YOU FOR USING FROG. PLEASE CLEAR YOUR LOCAL CACHE.
